### ISSUE TITLE
Sort defintions more carefully

### ISSUE THREAD

**Issue by lastland** [plclub/hs-to-coq#15]
<a href="https://github.com/nomeata"><img src="https://avatars2.githubusercontent.com/u/148037?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [nomeata](https://github.com/nomeata)**
_Thursday Sep 28, 2017 at 15:24 GMT_
_Originally opened as https://github.com/antalsz/hs-to-coq/issues/15_

----

We have to do a topological sort to mix instance declarations and value declarations, and also to get instance declarations in the right order. Currently, this uses `topoSortSentences`. I want to see if I can make this function, or another function, a bit better at preserving the original order, so that we have to emit less `order` edits when things are in the right order in the source code already. `examples/successors` is an example for that.

**Comment by lastland** [comment]
<a href="https://github.com/nomeata"><img src="https://avatars2.githubusercontent.com/u/148037?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nomeata](https://github.com/nomeata)**
_Wednesday Oct 11, 2017 at 19:21 GMT_

----

Would also fix the problem that the notations for operators are in the wrong order.

**Comment by lastland** [comment]
@Lysxia I remember that you did something relevant to this? Do you think your commit has resolved this issue?

**Comment by Lysxia** [comment]
Indeed one of my PRs partially addressed this: https://github.com/antalsz/hs-to-coq/pull/171

The main missing piece is to track dependencies through type class dictionaries. There probably is or should be an issue about that so we can close this one.
