### ISSUE TITLE
`.github/workflows/hs-to-coq.yml` only tests `ghc843`, but `hs-to-coq.cabal` claims it's tested with `GHC == 8.4.4, GHC == 8.6.5, GHC == 8.8.4 GHC == 8.10.1`

### ISSUE THREAD

**Issue by quinn-dougherty** [plclub/hs-to-coq#200]
Is `hs-to-coq.cabal` `tested-with` field out of date? or is someone running those tests locally? 

Should we just add more `ghc` versions to the `matrix` in `.github/workflows/hs-to-coq.yml`

**Comment by quinn-dougherty** [comment]
Same subject, but `coq` side:

https://github.com/plclub/hs-to-coq/blob/a67f4d1ef434a771a2e35786729e1e34a2a8175b/default.nix#L49

this line of `default.nix` claims that `coq` versions are supported that are not tested in ci.

**Comment by lastland** [comment]
The CI testing does test multiple GHC versions. It is done by: https://github.com/plclub/hs-to-coq/blob/1ed914595e6170e81fc71f8ef98724d51738db6d/.github/workflows/hs-to-coq.yml#L99

**Comment by quinn-dougherty** [comment]
When I look at the jobs `test`, `test-translation`, `test-container-extraction`, and `installing-haskell`, they only run for `ghc 8.4.3`. Intuitively, the executables built by the matrix `cross-build-hs-to-coq` should _each_ be tested in `test`, `test-translation`, `test-container-extraction`, right?

**Comment by Lysxia** [comment]
Ideally that should be the case. But if I recall correctly, it's only the hs-to-coq executable that can be built with 8.4-8.10. The Coq code (translations and proofs about core libraries) is still specialized to 8.4.

**Comment by lastland** [comment]
Ideally, that is the case. However, tasks like `test-translation` would actually fail if we switch the `ghc` version. The reason is not that there's something wrong with `hs-to-coq` (I believe), but the Haskell files in the `examples` are specific to certain ghc versions. For example, using ghc 8.10 on the `base` library from ghc 8.4 in `examples` would result in a parse error.

**Comment by lastland** [comment]
Close this for now.
